# GitHub Pages Configuration
# Arquivo especial que o GitHub Pages reconhece para configuração

# Define o arquivo principal como index-web.html
# (renomeado para index.html no deploy)

# Scripts de build automático para GitHub Actions
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Pages
      uses: actions/configure-pages@v2
      
    - name: Copy web version as main
      run: |
        cp index-web.html index.html
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1